### ISSUE TITLE
Connetction UI missing str key

### ISSUE THREAD

**Issue by MRhythm** [MRhythm/stationeers_localization#7]
All the aim-to-display with wire connections are missing the keys for "Power" and "Data".

And some device shows "input" missing translate key.

![Image](https://github.com/user-attachments/assets/c5bde5a5-704a-4488-b2fb-6affc9b1037d)

![Image](https://github.com/user-attachments/assets/3db3b6f4-4c39-4fdf-a397-eb9c1834a08f)

![Image](https://github.com/user-attachments/assets/97724853-9978-47ba-843f-6ae83c22dd1d)

**Comment by MattCaradusRW** [comment]
fixed

**Comment by MRhythm** [comment]
In version 24832, this bug still exists.

Did you forget to link <Key>Connection*</Key> to the game?
